const About = () => {
    return (
        <div>
            <h1>About</h1>
            <p>You dont need to change anything in your package.json for a server-side rendered app! Just keep the one that was generated by create-next-app.</p>
            <p>If you have an app with both SSR and SSG pages, also keep the default package.json, same as a fully SSR app!</p>
        </div>
    );
}

export default About;