import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <div>
      <h1>Homepage</h1>
      <p>You dont need to change anything in your package.json for a server-side rendered app! Just keep the one that was generated by create-next-app.</p>
      <p>If you have an app with both SSR and SSG pages, also keep the default package.json, same as a fully SSR app!</p>
    </div>
  )
}
